name: inkapus
favicon: null
layout_spectrum: 0.49889
typography_spectrum: 0.267254666890949
title: The Quiet Adventures of Iggy the Introverted Inkapus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82a6fc'
    - '#ffffff'
    - '#000000'
    - '#e2cd34'
    - '#de13e1'
  brandStrength: 0.5921429516747594
  lightness: 0.5
  saturation: 0.9132212391123176
  rhythmicContrast: 0.2019330516923219
purpose: []
